apiVersion: apps/v1.0
kind: Deployment
metadata:
  name: posty-app
spec:
  selector:
    matchLabels:
      app: quest-app
  replicas: 1
  template:
    metadata:
      labels:
        app: posty-app
    spec:
      containers:
        - name: posty-app
          image: mustafakacarmi/postyapp:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi